- uses: Platane/snk@v2.0.0-rc.3
  with:
    # github user name to read the contribution graph from (**required**)
    # using action context var `github.repository_owner` or specified user
    github_user_name: baggiogiacomo

    # list of files to generate.
    # one file per line. Each output can be customized with options as query string.
    outputs: |
      dist/github-snake.svg
      dist/github-snake.svg?palette=github-dark
      dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
